env:
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars:
  - error
  - args: after-used
    argsIgnorePattern: ^unused
    varsIgnorePattern: ^unused
