export const daysOfWeek = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const modesOfTransport = [
  "Bicycle",
  "Bus",
  "Car",
  "Motorbike/scooter",
  "Taxi/ride share",
  "Train/tram",
  "Walking/running",
  "Other",
];

export const departments = [
  "Active & Healthy Lifestyles",
  "Bendigo Art Gallery",
  "Bendigo Venues & Events",
  "Business Services & Economic Development",
  "Business Transformation",
  "Climate Change and Environment",
  "Community Partnerships",
  "Community Wellbeing",
  "Engineering",
  "Financial Strategy",
  "GovHub & Our Future Workplace",
  "Governance",
  "Healthy GREATER Bendigo",
  "Information Management",
  "Parks & Open Spaces",
  "People & Culture",
  "Property Services",
  "Resource Recovery & Education",
  "Strategic Planning",
  "Safe & Healthy Environments",
  "Statutory Planning",
  "Tourism & Major Events",
  "Works",
];
