name: deploy cloud function

on:
  push:
    branches: [ main ]
    paths:
      - 'cloud-functions/**.js'
      - 'cloud-functions/package*.json'
      - '.github/workflows/deploy-cloud-function.yml'

jobs:
  deploy-cloud-function:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: Checkout repository
      uses: actions/checkout@v2

    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: sheeter
        credentials: ${{ secrets.GCP_SA_KEY }}
        region: australia-southeast1
        runtime: nodejs14
        source_dir: cloud-functions

    # Example of using the output
    - id: test
      run: curl "${{ steps.deploy.outputs.url }}"
